"""联合 App 配置，作用类似 C 工程的 config.h。"""
MODE_QR = "QR"
MODE_OBJECT = "OBJECT"
START_MODE = "IDLE"  # wait for MCU; USER can start standalone QR before UART ownership
KEY_DEBOUNCE_MS = 180
KEY_LONG_PRESS_MS = 1500
QR_WIDTH, QR_HEIGHT = 1920, 1440  # 07工程第36档；用户实测选择，中心50% ROI不变。
OBJECT_WIDTH, OBJECT_HEIGHT = 480, 320
QR_ROI_FRACTION = 0.50
QR_MAX = 1
QR_KEEP_FRAMES = 15
OBJECT_BOX_HOLD_MS = 200  # 仅屏幕：漏检后保留旧框200毫秒；0立即消失，不延迟UART。
TASK_CONFIRM_FRAMES = 3  # 同一合法三码连续3帧才锁定；空帧、冲突或非法码重新计数。
MODEL_FILE = "model_9564.mud"
CONF_THRESHOLD = 0.35
MAX_OBJECTS = 10
DUAL_BUFFER = False
CLASS_NAMES = ("oblate", "cylinder", "truncated_cone", "blue_ball", "red_ball", "green_ball", "red_target", "blue_target", "green_target", "black_barrel")
CLASS_NAMES_CN = ("扁圆物体", "圆柱体", "圆台体", "蓝球", "红球", "绿球", "红靶子", "蓝靶子", "绿靶子", "黑桶")
QR_COLOR_NAMES_CN = {"1": "红", "2": "绿", "3": "蓝"}
QR_SHAPE_NAMES_CN = {"1": "圆柱", "2": "圆锥", "3": "腰鼓"}
QR_COLOR_CODES = {"1": "R", "2": "G", "3": "B"}
QR_SHAPE_CODES = {"1": "Cyl", "2": "Cone", "3": "Drum"}
UART_ENABLED = True
UART_DEVICE = "/dev/ttyS1"
UART_BAUDRATE = 115200
UART_TX_PIN = "A19"
UART_RX_PIN = "A18"
UART_TRACE = True
UART_TRACE_EVERY_N_FRAMES = 10
UART_WRITE_ATTEMPTS = 8
DISPLAY_ENABLED = True
PRINT_EVERY_N_FRAMES = 10
STATUS_TEXT_SCALE = 5
BOX_TEXT_SCALE = 2  # QR结果基础字号；保留当前扫码显示设置。
OBJECT_TEXT_SCALE = 3  # 物体标签和中心X/Y；按实际屏幕缩小比例补偿。
